name: Deploy AWS

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 3.1.x
    
    - name: Restore dependencies
      run: dotnet restore
    
    - name: Build
      run: dotnet build --configuration Release --no-restore
      
    - name: Test
      run: dotnet test --no-build --no-restore --verbosity normal
      
    - name: Publish
      run: dotnet publish -c Release -o '${{ github.workspace }}/out'
      
    - name: Zip Package
      run: 
        zip -r deploy.zip . -x '*.git*'
        
    - name: Deploy to EB
      uses: einaregilsson/beanstalk-deploy@v20
      with:
        aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        application_name: Webapi
        environment_name: Webapi-env
        version_label: ${{ github.run_id }}
        region: us-east-1
        deployment_package: ${{ github.workspace }}/deploy.zip
        
        
